### ISSUE TITLE
Unable to resize Blizzy's Toolbar when KCT icon is transferred to it.

### ISSUE THREAD

**Issue by GJNelson7030** [linuxgurugamer/KCT#36] opened 2019-11-11 04:40 UTC
I'm having issues with resizing Blizzy's Toolbar when I transfer the KCT icon to it using the Toolbar Controller mod. I thought I corrected it when I removed the 2 mods (Kerbal Wind Tunnel and SmartStage) that were outdated for KSP v1.8.1, but it turned out the problems were due to Kerbal Construction Time and Toolbar Controller. Toolbar Controller works fine with other mods, so my thoughts are it's something with the KCT mod.

[KSP.log](https://github.com/linuxgurugamer/KCT/files/3829725/KSP.log)

**Comment by GJNelson7030** [comment] 2019-11-11 04:42
I'm ingame at the moment and that's the latest KSP.log file. I can provide anything else if needed?

**Comment by lpgagnon** [comment] 2019-11-13 04:04
Seeing the same issue. KSP 1.7.3, KCT 1.4.6.14, Toolbar 1.7.22.2, Toolbar Control 0.1.0.2

**Comment by linuxgurugamer** [comment] 2019-11-13 13:39
I have reproduced it, but haven't yet been able to fix.
For now, since there is an easy workaround,  it's not going to be fixed.  Eventually, but not now

**Comment by linuxgurugamer** [comment] 2020-01-19 00:41
Fixed in latest beta:
https://github.com/linuxgurugamer/KCT/releases/tag/1.4.7.10

**Closed as completed by linuxgurugamer** 2020-01-19 00:41 UTC
